"""initial schema

Revision ID: c254d08a60f5
Revises: 
Create Date: 2026-05-07 17:19:30.135902
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


revision = 'c254d08a60f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('length_km', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('gps_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constructor_ref', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constructor_ref')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_ref', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('forename', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_ref')
    )
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_year', 'round', name='uq_race_season_round')
    )
    op.create_table('lap_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('gap_to_leader_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'lap', name='uq_lap_driver_race')
    )
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('stop_number', sa.Integer(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tire_in', sa.String(length=10), nullable=True),
    sa.Column('tire_out', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'stop_number', name='uq_pit_driver_stop')
    )
    op.create_table('race_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('lap_start', sa.Integer(), nullable=True),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'lap', name='uq_telemetry_driver_lap')
    )
    op.create_index('idx_lap_times_race', 'lap_times', ['race_id'])
    op.create_index('idx_lap_times_driver', 'lap_times', ['driver_id'])
    op.create_index('idx_pit_stops_race', 'pit_stops', ['race_id'])
    op.create_index('idx_telemetry_race', 'telemetry_paths', ['race_id'])
    op.create_index(
        'idx_embeddings_vector',
        'race_embeddings',
        ['embedding'],
        postgresql_using='ivfflat',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_embeddings_vector', table_name='race_embeddings')
    op.drop_index('idx_telemetry_race', table_name='telemetry_paths')
    op.drop_index('idx_pit_stops_race', table_name='pit_stops')
    op.drop_index('idx_lap_times_driver', table_name='lap_times')
    op.drop_index('idx_lap_times_race', table_name='lap_times')
    op.drop_table('telemetry_paths')
    op.drop_table('scenarios')
    op.drop_table('safety_cars')
    op.drop_table('race_results')
    op.drop_table('race_embeddings')
    op.drop_table('pit_stops')
    op.drop_table('lap_times')
    op.drop_table('races')
    op.drop_table('seasons')
    op.drop_table('drivers')
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
